export const ZjRulesList = [
    {
        id: "1",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "及时性",
        ruleName: "及时性质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段（数据类型为日期时间类型）的最新日期质检，与设定的研判条件进行比对。符合条件的认为通过质检，不符合条件的认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据更新及时性不足"
    },
    {
        id: "2",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "一致性",
        ruleName: "主外键一致性质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，与设定的从表字段进行数据比对。质检对象表中，能关联到从表的数据认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "主外键关联不成功"
    },
    {
        id: "3",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "完整性",
        ruleName: "空值质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段（该字段业务上不允许为空），若数据为空值，则认为不通过质检，否则认为通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不可为空"
    },
    {
        id: "4",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "唯一值质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段（该字段业务上不允许有重复值），若数据为重复值，则重复的数据都认为不通过质检，否则认为通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不可重复"
    },
    {
        id: "5",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "值域校验",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，根据设置关联的标准代码集，若数据在代码集的代码值域内，则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据超出代码集范围"
    },
    {
        id: "6",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "重复值质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段（该字段业务上不允许有唯一值），若数据为唯一值，则唯一的数据认为不通过质检，否则认为通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不可唯一"
    },
    {
        id: "7",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "规范性",
        ruleName: "身份证校验",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，是否符合身份证号的标准规范，若符合则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合身份证号规则"
    },
    {
        id: "8",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "规范性",
        ruleName: "手机号校验",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，是否符合手机号的标准规范，若符合则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合手机号规则"
    },
    {
        id: "9",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "规范性",
        ruleName: "邮箱校验",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，是否符合邮箱地址的标准规范，若符合则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合邮箱地址规则"
    },
    {
        id: "10",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "规范性",
        ruleName: "标准数据元校验",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，是否符合标准数据元中的标准规范，若符合则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合数据元标准"
    },
    {
        id: "11",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "前缀/后缀质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，是否符合前缀/后缀的定义，若符合则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合前缀/后缀要求"
    },
    {
        id: "12",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "前缀/后缀（非）质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，是否符合前缀/后缀（非）的定义，若符合则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合前缀/后缀（非）要求"
    },
    {
        id: "13",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "最大/最小长度质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，数据长度是否在定义的范围内，若在范围内则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合最大/最小长度要求"
    },
    {
        id: "14",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "数字字段质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，是否全为数值，再根据定义的判断规则，若符合则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据（不）应全为数值"
    },
    {
        id: "15",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "枚举质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，匹配定义的枚举值组，若匹配成功则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合枚举范围要求"
    },
    {
        id: "16",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "正则质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，匹配定义的正则表达式，若匹配成功则认为通过质检，否则认为不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不匹配正则表达式"
    },
    {
        id: "17",
        createBy: "system",
        updateBy: null,
        createTime: "2022-07-01 00:00:01",
        updateTime: null,
        delFlag: 0,
        controlDimension: "准确性",
        ruleName: "自定义质检",
        rulesHierarchy: "字段级",
        templateDescription: "取质检采样范围内的数据，研判某一字段，根据用户定义的SQL语句（支持跨库的联表查询），slect出来的数据则认为通过质检，否则任务不通过质检。",
        affectLevel: "A",
        state: "内置",
        head: "",
        reasonDescription: "数据不符合自定义的质检规则"
    }
]
